#!/usr/bin/env bash
# -*- ENCODING: UTF-8 -*-
#
# Copyright (c) 2015 Nelson Martell (http://nelson6e65.github.io)
#
# Licensed under The MIT License (MIT)
#
# For full copyright and license information, please see the LICENSE
# Redistributions of files must retain the above copyright notice.
#

if [[ -z $SCRIPT_DIR ]]; then
    # Current file directory
    declare -xr SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
fi

if [[ -z $ROOT_DIR ]]; then
    # Root directory
    declare -xr ROOT_DIR=$(dirname "$SCRIPT_DIR")
fi

. "$ROOT_DIR/config/init"

# Return value
declare -i errores=$E_NONE

echo_separator '_'
echo_separator '='
echo_header "Generating .RPM installer"
echo_separator '=';

alert_debug "Generating .RPM installer" "Fedora Atom Builder"

# pause

log_cd "$SRC_DIR/atom"
errores=$(( errores | $? ))

if [[ $errores -eq 0 ]]; then
    echo_header "Building RPM installer" "-"

    script/grunt mkrpm

    if [[ $? -eq 0 ]]; then
        show_success "RPM builded sucessfully" "Generating .RPM installer"

        dir="$ROOT_DIR/dist"
        echo_header "Getting a copy to DIST directory" "-"
        alert_debug "$dist" "Getting a copy to DIST directory..."

        declare sumary='Unable to copy builded RPM to dist directory'
        declare message=''

        # Checks if sources directory for sources:
        if [[ -e "$dir" ]]; then
            if [[ ! -d "$dir" ]]; then
                message="'$dir' must to be a directory."
                message+="\n'$dir' exists, but can not be used to copy resulting build."

                # TODO: Add autosolver

                errores=$((errores | E_COPY_BUILDED_IN_DIST_DIRECTORY))
            fi
        else
            # Try to solve it, by creating the folder...
            mkdir "$dir"

            if [[ $? -ne 0 ]]; then
                message="\n'${dir}' directory do not exists and could not be created."

                errores=$((errores | E_COPY_BUILDED_IN_DIST_DIRECTORY))
            fi
        fi

        if [[ ! -w "$dir" ]]; then
            message="'$dir' must to have write permissions."
            message+="'$dir' directory exists, but can not be used to copy resulting build."
            message+=" Grand write permissions manually the next time you run this script."

            # TODO: Add autosolver

            errores=$((errores | E_COPY_BUILDED_IN_DIST_DIRECTORY))
        fi

        cp out/rpm/atom-*.rpm "${dir}/"

        if [[ $? -eq 0 ]]; then
            message="Atom Editor installer (.rpm file) copied to '${dir}'"
            message+="directory, ready to be installed."
            show_success  "${message}" "Resulting installer copied sucessfully"
        else
            message+="You must install '*.rpm' from '${pwd}/out/rpm/' directory instead."

            show_warning "${message}" "${sumary}"
            errores=$((errores | E_COPY_BUILDED_IN_DIST_DIRECTORY))
        fi

    else
        show_error "Failed to build RPM installer. Did you builded sources?" "Unable to generate .RPM installer"
        errores=$(( errores | E_BUILD_RPM ))
    fi
else
    show_error "Atom sources are not reachable. Did you skipped getting sources?" \
        "Unable to generate RPM"
    errores=$(( errores | E_BUILD_RPM ))
fi

echo_separator '_'

exit $errores # TODO: Fix returning values
