#!/usr/bin/env bash
# -*- ENCODING: UTF-8 -*-
#
# Copyright (c) 2015 Nelson Martell (http://nelson6e65.github.io)
#
# Licensed under The MIT License (MIT)
#
# For full copyright and license information, please see the LICENSE
# Redistributions of files must retain the above copyright notice.
#

if [[ -z $SCRIPT_DIR ]]; then
    # Current file directory
    declare -xr SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
fi

if [[ -z $ROOT_DIR ]]; then
    # Root directory
    declare -xr ROOT_DIR=$(dirname "$SCRIPT_DIR")
fi

. "$ROOT_DIR/config/init"

# Return value
declare -i errores=$E_NONE

echo_separator '_'
echo_separator '='
echo_header "Generating .RPM installer"
echo_separator '=';

# pause

log_cd "$SRC_DIR/atom"
errores=$(( errores | $? ))

if [[ $errores -eq 0 ]]; then
    echo_header "Building RPM installer" "-"

    script/grunt mkrpm

    echo_result

    if [[ $? -eq 0 ]]; then
        echo_header "Getting a copy to DIST directory" "-"

        dir="$ROOT_DIR/dist"

        # Checks if sources directory for sources:
        if [[ -e $dir ]]; then
            if [[ ! -d $dir ]]; then
                echo "Error: '$dir' must to be a directory."
                echo "'$dir' exists, but can not be used to copy resulting build."
                echo "You must install '*.rpm' from temporal directory instead."

                # TODO: Add autosolver

                errores=$((errores | E_COPY_BUILDED_IN_DIST_DIRECTORY))
            fi
        else
            # Try to solve, creating the folder...
            mkdir "$dir"
            if [[ $? -ne 0 ]]; then
                errores=$((errores | E_COPY_BUILDED_IN_DIST_DIRECTORY))
            fi
        fi

        if [[ ! -w $dir ]]; then
            echo "Error: '$dir' must to have write permissions."
            echo -n "'$dir' directory exists, but can not be used to copy resulting build."
            echo " Grand write permissions manually the next time you run this script."
            echo "You must install '*.rpm' from temporal directory instead."

            # TODO: Add autosolver

            errores=$((errores | E_COPY_BUILDED_IN_DIST_DIRECTORY))
        fi

        cp out/rpm/atom-*.rpm $dir

        echo_result
        if [[ $? -ne 0 ]]; then
            echo "Unable to copy builded file."
            echo "You must install '*.rpm' from temporal directory instead."
            errores=$((errores | E_COPY_BUILDED_IN_DIST_DIRECTORY))
        fi

    else
        errores=$(( errores | E_BUILD_RPM ))
    fi
else
    echo "Unable to generate RPM"
    echo_result $errores
    errores=$(( errores | E_BUILD_RPM ))
fi

echo_separator '_'

exit $errores
