#!/usr/bin/env bash
# -*- ENCODING: UTF-8 -*-
#
# Copyright (c) 2015 Nelson Martell (http://nelson6e65.github.io)
#
# Licensed under The MIT License (MIT)
#
# For full copyright and license information, please see the LICENSE
# Redistributions of files must retain the above copyright notice.
#

if [[ -z $SCRIPT_DIR ]]; then
    # Current file directory
    declare -xr SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
fi

if [[ -z $ROOT_DIR ]]; then
    # Root directory
    declare -xr ROOT_DIR=$(dirname "$SCRIPT_DIR")
fi

. "$ROOT_DIR/config/init"

# Return value
declare -i errores=$E_NONE

echo_separator '_'
echo_separator '='
echo_header "Building Atom"
echo_separator '=';

# pause

log_cd "$SRC_DIR/atom"
errores=$(( errores | $? ))

if [[ $errores -eq 0 ]]; then
    echo_header "Building source code" "-"

    show_info "This operation may take several minutes to get completed." \
        "Building source code..."
    echo " Just leave me here making my job. ;)"

    script/clean || show_warning "Failed to clean old builded"

    script/build

    if [[ $? -eq 0 ]]; then
        show_success "Atom sources are ready to be compiled into .rpm installer." \
            "Atom sources builded successfully!"
    else
        show_error "Errors on building sources" "Unable to build sources"
        errores=$(( errores | E_BUILD_SOURCES ))
    fi
else
    show_error "Atom sources are not reachable. Did you got the sources?" \
        "Unable to build sources"
    errores=$(( errores | E_BUILD_SOURCES ))
fi

echo_separator '_'

exit $errores
